// Generated by CoffeeScript 1.6.3
(function() {
  window.Nick = (function(nick, $) {
    nick.init = function() {
      nick.pageSetup();
      return nick.uiBinding();
    };
    return nick;
  })(window.Nick, jQuery);

  $(function() {
    return window.Nick.init();
  });

}).call(this);
