// Generated by CoffeeScript 1.6.3
(function() {
  window.Nick = (function(nick, $) {
    var $body;
    $body = $("body");
    nick.el = (function() {
      return {
        $html: $("html"),
        $body: $body,
        $header: $body.children("header"),
        $footer: $body.children("footer"),
        $lazyBg: $("[data-lazy-bg]")
      };
    })();
    return nick;
  })(window.Nick || {}, jQuery);

}).call(this);
