// Generated by CoffeeScript 1.6.3
window.Nick = (function(nick, $) {
  nick.uiBinding = function() {
    return nick.el.$body.on("click", function() {
      return $(this).addClass("clicked");
    });
  };
  return nick;
})(window.Nick, jQuery);
